### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by waldenn** [stevenliuyi/wikidata-prop-explorer#3]
Please add a LICENSE file. Thanks. Nice project!

**Comment by valerio-bozzolan** [comment]
Yes, please add a Free license <3

Note that this is actually a requirement for any Toolforge Tool :)

**Comment by stevenliuyi** [comment]
Thanks for the reminder. The MIT license has been added now.

**Comment by valerio-bozzolan** [comment]
You're the best :rocket:
