### ISSUE TITLE
Properties missing?

### ISSUE THREAD

**Issue by valerio-bozzolan** [stevenliuyi/wikidata-prop-explorer#40]
For some reasons I'm not able to find the property "copyright license"

![screenshot of wikidata prop explorer](https://github.com/stevenliuyi/wikidata-prop-explorer/assets/6052909/d869c265-51a5-434b-9df0-6061d7e03953)

I thought that this one should appear:

https://www.wikidata.org/wiki/Property:P275

Am I doing something wrong?

**Comment by valerio-bozzolan** [comment]
I cannot also find P27 "country", not even ordering by ID

![image](https://github.com/user-attachments/assets/a60c5ded-d61b-4614-a21d-9e9f245eab72)

Is there a problem with every property that starts with "27"? :thinking: lol

**Comment by thadguidry** [comment]
Try the right property identifier?  `P17` and not `P27` ?  Do not feel bad, we all do it sometimes. :-)
![image](https://github.com/user-attachments/assets/873d50b3-a77d-409a-bd3f-e7d17ddb68ad)

**Comment by valerio-bozzolan** [comment]
I really mean that this does not appear, not by ID, not by partial name "country"

https://wikidata.org/wiki/Property:P27

**Comment by valerio-bozzolan** [comment]
Cannot reproduce 🤔 lol
